"""empty message

Revision ID: 68e338e85c66
Revises: 6902477dcd82
Create Date: 2025-09-21 22:28:24.808812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e338e85c66'
down_revision: Union[str, Sequence[str], None] = '6902477dcd82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatus'),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('NEW', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
