"""empty message

Revision ID: 9b5ca9495bdc
Revises: 68e338e85c66
Create Date: 2025-09-22 18:50:50.929051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5ca9495bdc'
down_revision: Union[str, Sequence[str], None] = '68e338e85c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['telegram_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
